<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataView_Behavioral_MM11" nsURI="DV_Beh_MM1" nsPrefix="DV_MM1">
  <eClassifiers xsi:type="ecore:EClass" name="NodeBehavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkableElement" abstract="true" eSuperTypes="#//NodeBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="#//LinkableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//NodeBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//LinkableElement" eOpposite="#//LinkableElement/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//LinkableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveData" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRecipient" eType="#//DataRepresentation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendData" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRecipient" eType="#//DataRepresentation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generate" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ingest"/>
  <eClassifiers xsi:type="ecore:EClass" name="Store"/>
  <eClassifiers xsi:type="ecore:EClass" name="Analyze"/>
  <eClassifiers xsi:type="ecore:EClass" name="Consume"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ingest"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reduce Noise"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tranfrom"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compress"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integrate" eSuperTypes="#//Ingest.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identify"/>
  <eClassifiers xsi:type="ecore:EClass" name="Filter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Validate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classify" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sort" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tranform" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cleaning" eSuperTypes="#//Process"/>
 
</ecore:EPackage>
