<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataView_MM" nsURI="MM" nsPrefix="DV_MM">
  <eClassifiers xsi:type="ecore:EClass" name="DataArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//DataNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NodeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Outgoing" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/from"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Incoming" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/to"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRepresentation" lowerBound="1"
        upperBound="-1" eType="#//DataRepresentation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//DataPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="1" eType="#//NodeBehavior"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//DataNode"
        eOpposite="#//DataNode/Outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//DataNode"
        eOpposite="#//DataNode/Incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Source" lowerBound="1"
        eType="#//OutDataPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Destination" lowerBound="1"
        eType="#//InDataPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPort" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InDataPort" eSuperTypes="#//DataPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutDataPort" eSuperTypes="#//DataPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeBehavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data Formats" abstract="true" eSuperTypes="#//DataRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Structured" abstract="true" eSuperTypes="#//Data%20Formats"/>
  <eClassifiers xsi:type="ecore:EClass" name="SemiStructured" abstract="true" eSuperTypes="#//Data%20Formats"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnStructured" abstract="true" eSuperTypes="#//Data%20Formats"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data Storage" abstract="true" eSuperTypes="#//DataRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewSQL" eSuperTypes="#//Data%20Storage"/>
  <eClassifiers xsi:type="ecore:EClass" name="File System" eSuperTypes="#//Data%20Storage"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoSQL" abstract="true" eSuperTypes="#//Data%20Storage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data Processing Type" abstract="true"
      eSuperTypes="#//DataRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealTime" eSuperTypes="#//Data%20Processing%20Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Batch" eSuperTypes="#//Data%20Processing%20Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data Location" eSuperTypes="#//DataRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cloud" eSuperTypes="#//Data%20Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="On-Premise" eSuperTypes="#//Data%20Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multidimensional" eSuperTypes="#//Data%20Storage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Key-Value" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multi-media" eSuperTypes="#//UnStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="GPS data" eSuperTypes="#//UnStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="Office File" eSuperTypes="#//UnStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="Email" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="SMS" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDI " eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="RDF" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="HTML " eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="Excel" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="CSV" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="JSON" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="XML" eSuperTypes="#//SemiStructured"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalDB" eSuperTypes="#//Structured"/>
  <eClassifiers xsi:type="ecore:EClass" name="Historical " eSuperTypes="#//NewSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Real-Time" eSuperTypes="#//NewSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stream " eSuperTypes="#//NewSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="Timestamp" eSuperTypes="#//NewSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="HDFS" eSuperTypes="#//File%20System"/>
  <eClassifiers xsi:type="ecore:EClass" name="GFS " eSuperTypes="#//File%20System"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFS" eSuperTypes="#//File%20System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Blobseer " eSuperTypes="#//File%20System"/>
  <eClassifiers xsi:type="ecore:EClass" name="GPFS " eSuperTypes="#//File%20System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Protobuf" eSuperTypes="#//SemiStructured"/>
</ecore:EPackage>
