<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataView_MM" nsURI="MM" nsPrefix="DV_MM">
  <eClassifiers xsi:type="ecore:EClass" name="DataElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Connector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NodeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRepresentation" eType="#//DataRepresentation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeBehavior" eType="#//NodeBehavior"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRepresentation" eType="#//DataRepresentation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkBehavior" eType="#//LinkBehavior"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataLinkTypes" upperBound="-1"
        eType="#//DataLinkTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeAction" eType="#//NodeAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkAction" eType="#//LinkAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeAction" abstract="true">
    <eOperations name="sentData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="receiveData" eType="#//DataRepresentation"/>
    <eOperations name="storeData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkAction" abstract="true">
    <eOperations name="getNext" eType="#//Node"/>
    <eOperations name="getPrevious" eType="#//Node"/>
    <eOperations name="Transmit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataLinkType" upperBound="-1"
        eType="#//DataLinkTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerateData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="IngestData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="StoreData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LableData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceptData" eSuperTypes="#//NodeAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthinticateData" eSuperTypes="#//LinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValidateData" eSuperTypes="#//LinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MonitorData" eSuperTypes="#//LinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MitigateData" eSuperTypes="#//LinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SendingAlarmData" eSuperTypes="#//LinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFormat" eType="#//DataFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensitivityLevel" eType="#//SensitivityLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProcessingType" eType="#//DataProcessingType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataStorageType" eType="#//DataStorageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFormat" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredData" abstract="true" eSuperTypes="#//DataFormat"/>
  <eClassifiers xsi:type="ecore:EClass" name="SemiStructuredData" abstract="true"
      eSuperTypes="#//DataFormat"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnStructuredData" abstract="true" eSuperTypes="#//DataFormat"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataStorageType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HDFS" eSuperTypes="#//DataStorageType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relational" eSuperTypes="#//DataStorageType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multidimensional" eSuperTypes="#//DataStorageType"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoSQL" abstract="true" eSuperTypes="#//DataStorageType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentOriented" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnOriented" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="GraphsDatabase" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValue" eSuperTypes="#//NoSQL"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataProcessingType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealTime_Processing" eSuperTypes="#//DataProcessingType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Batch_Processing" eSuperTypes="#//DataProcessingType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalDB" eSuperTypes="#//StructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForeignKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refForginKey" eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XML" eSuperTypes="#//SemiStructuredData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlNodes" upperBound="-1"
        eType="#//XMLNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//XMLNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeAttributes" upperBound="-1"
        eType="#//NodeAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute_Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JSON" eSuperTypes="#//SemiStructuredData"/>
  <eClassifiers xsi:type="ecore:EClass" name="CSV" eSuperTypes="#//SemiStructuredData"/>
  <eClassifiers xsi:type="ecore:EClass" name="Excel" eSuperTypes="#//SemiStructuredData"/>
  <eClassifiers xsi:type="ecore:EClass" name="HTML" eSuperTypes="#//SemiStructuredData"/>
  <eClassifiers xsi:type="ecore:EClass" name="RDF" eSuperTypes="#//SemiStructuredData"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDI" eSuperTypes="#//SemiStructuredData"/>
  <eClassifiers xsi:type="ecore:EClass" name="SMS" eSuperTypes="#//SemiStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Email" eSuperTypes="#//SemiStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachmentData" upperBound="-1"
        eType="#//UnStructuredData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multimedia" abstract="true" eSuperTypes="#//UnStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_Multi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audio" eSuperTypes="#//Multimedia"/>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="#//Multimedia"/>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//Multimedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transparency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="animation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GPSData" eSuperTypes="#//UnStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OfficeFile" abstract="true" eSuperTypes="#//UnStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="font" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textsize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Logs" eSuperTypes="#//OfficeFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="WordFile" eSuperTypes="#//OfficeFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="PDFFile" eSuperTypes="#//OfficeFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextFile" eSuperTypes="#//OfficeFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorData" eSuperTypes="#//UnStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicalsize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measuringRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensivity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reproducibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linearity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bandwidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hystersis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatureRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataLinkTypes">
    <eLiterals name="CONTINUOUS" value="1"/>
    <eLiterals name="INTERMITTENT" value="2"/>
    <eLiterals name="BATCHES" value="3"/>
    <eLiterals name="STRUCTURED" value="4"/>
    <eLiterals name="LABELLED" value="5"/>
    <eLiterals name="PREPROCESSED" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensitivityLevel">
    <eLiterals name="High" value="1"/>
    <eLiterals name="Medium" value="2"/>
    <eLiterals name="Low" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataBaseLocation">
    <eLiterals name="Centralized" value="1"/>
    <eLiterals name="Distributed" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataBaseDesign">
    <eLiterals name="Operational_OLTP" value="1"/>
    <eLiterals name="Analytical_OLAP" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataBaseHosting">
    <eLiterals name="On_Premises" value="1"/>
    <eLiterals name="Cloud" value="2"/>
  </eClassifiers>
</ecore:EPackage>
